189 i/o toggle
javaTheHutts/Java-the-Hutts pull request #192
Opened 2017-10-10 21:41 UTC by Nicvaniek

2017-10-10 22:13 UTC, AndreasNel requested changes
2 small changes. One of which I am deeply disappointed in you 😉 and one that seems small, but will have a large impact on the rest of this pull request.

2017-10-10 22:13 UTC, AndreasNel commented on src/main/python/image_preprocessing/pipeline.py
> +        print("-------------------------------------------------------")
No.

2017-10-10 22:13 UTC, AndreasNel commented on src/main/python/image_preprocessing/pipeline.py
> +    def process_text_extraction(self, useIO, image, remove_face=False):
Make `useIO` have a default value of `False`

2017-10-10 22:19 UTC, Nicvaniek commented on src/main/python/image_preprocessing/pipeline.py
> +        print("-------------------------------------------------------")
😂😂😂

2017-10-11 06:42 UTC, nellstephanj commented on src/main/python/image_preprocessing/pipeline.py
> +        print("-------------------------------------------------------")
🤦🏼‍♂

2017-10-12 14:10 UTC, AndreasNel requested changes

2017-10-12 14:10 UTC, AndreasNel commented on src/main/python/image_preprocessing/pipeline.py
> +            useIO (boolean): Wheteher or not to write images to disk
Wheteher -> Whether

2017-10-12 14:57 UTC, AndreasNel approved these changes

2017-10-12 14:58 UTC, merged